services:
  - type: web
    name: evento-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: evento-db
          property: connectionString
      - key: TICKETMASTER_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false

databases:
  - name: evento-db
    databaseName: event_booking_system
    user: evento_user
    plan: free