services:
  # Backend Service
  - type: web
    name: evento-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: evento-db
          property: connectionString
      - key: TICKETMASTER_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: web
    name: evento-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishing: true
    publishDirectory: dist
    buildFilter:
      paths:
        - src/**/*.{js,jsx,ts,tsx}
        - public/**/*
        - index.html
        - package.json
        - vite.config.js
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        value: https://evento-backend.onrender.com
      - key: VITE_TICKETMASTER_API_KEY
        sync: false

# Database Service
databases:
  - name: evento-db
    databaseName: event_booking_system
    user: evento_user
    plan: free